version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.9
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.32
    - 14.14.34
    - 14.14.37
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
