language: python
python:
  - "3.7"
env:
  - SERVER=master ACTION=test
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.35.0/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install 12 # for Node v12
  - node --version
  - npm install
  - curl https://raw.githubusercontent.com/Kinto/kinto/master/requirements.txt > versions.txt
  - pip install https://github.com/Kinto/kinto/zipball/master --constraint versions.txt
  - if [[ $SERVER && $SERVER != "master" ]]; then pip install kinto==$SERVER; fi
  - if [[ $SERVER && $SERVER == "master" ]]; then pip install https://github.com/Kinto/kinto/zipball/master; fi
  - pip install kinto-attachment
  - export KINTO_PSERVE_EXECUTABLE=pserve
script:
  - npm $ACTION
